### ISSUE TITLE
Artik port to custom PCB 

### ISSUE THREAD

**Issue by andrewjaykeller** [resin-os/resin-artik#124]
What are the steps for ensuring this code base works on our custom PCB with artik 530s? How do you know it’s an eagleeye vs a dev board?

**Comment by floion** [comment]
This is either PRed by the interested party in this repository and that somebody maintains and ensures each release is tested and validated working on Balena (Resin).
Or we can add and maintain support for a custom board (this needs a discussion with the sales team)

**Comment by andrewjaykeller** [comment]
Do you have any links for what to change? I.e. how did you know how to support the eagleeye?

**Comment by floion** [comment]
Here is the guide for adding support for new boards to Balena: https://github.com/balena-os/meta-balena/blob/master/contributing-device-support.md

**Comment by andrewjaykeller** [comment]
@floion i'm not really trying to add a new device, but I'm trying to use the Artik 530s on a different PCB, the main reason i picked this board is because resin (balena) suggested it.

**Comment by andrewjaykeller** [comment]
@floion I started digging down more into the platform ID and was wondering what the platform ID for the artiks are?

There is a function called [os_get_platform](https://github.com/SamsungARTIK/artik-sdk/blob/94f7890006816c005b39e635b56055608b369e9d/src/modules/base/module/linux_module.c#L257), how do I set this with balena?

If I get an Artik 530s from DigiKey and mount it on a board, what is the `platid` set as?
